package org.teiid.authoring.client.dialogs;

public enum UiEventType {
    CREATE_SOURCE_OK, 
    CREATE_SOURCE_CANCEL,
    DELETE_SOURCE_OK, 
    DELETE_SOURCE_CANCEL,
    QUERY_RESULT_DISPLAYER_REFRESHED_OK, 
    QUERY_RESULT_DISPLAYER_REFRESHED_NOROWS,
    QUERY_RESULT_DISPLAYER_REFRESHED_ERROR;
}
