package org.teiid.authoring.client.dialogs;

public enum UiEventType {
    CREATE_SOURCE_OK, 
    CREATE_SOURCE_CANCEL,
    DELETE_SOURCE_OK, 
    DELETE_SOURCE_CANCEL,
    DELETE_SERVICE_OK, 
    DELETE_SERVICE_CANCEL,
    SOURCE_RENAME_OK, 
    SOURCE_RENAME_CANCEL,
    SOURCE_REDEPLOY_OK, 
    SOURCE_REDEPLOY_CANCEL,
    SOURCE_CHANGETYPE_OK,
    SOURCE_CHANGETYPE_CANCEL,
    VIEW_EDITOR_CHANGED,
    DATA_SOURCE_DEPLOY_STARTING,
    DATA_SOURCE_DEPLOY_SUCCESS,
    DATA_SOURCE_DEPLOY_FAIL,
    QUERY_RESULT_DISPLAYER_REFRESHED_OK, 
    QUERY_RESULT_DISPLAYER_REFRESHED_NOROWS,
    QUERY_RESULT_DISPLAYER_REFRESHED_ERROR;
}
